INFO   :: 11:07:03: root                       FlatOntologyManager.py <_set_ontology>93 :  Loading ontology: ontology/ontologies/Films-rules.json
INFO   :: 11:07:03: root                            FlatOntologyManager.py <_set_db>109 :  Loading database: ontology/ontologies/Films-dbase.db
INFO   :: 11:07:03: root                                      pydial.py <initialise>374 :  Seed = 117
INFO   :: 11:07:03: root                                      pydial.py <initialise>375 :  Root = /home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial
DIAL   :: 11:07:03: root                                   pydial.py <chat_command>1126 :  *** Chatting with policies []: ***
INFO   :: 11:07:03: root                                    Agent.py <_hand_control>453 :  Launching Dialogue Manager for domain: Films
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      RegexSemI.py <__init__>83 :  No rTYPE regex has been set.
WARNING:: 11:07:03: root                                      HDCPolicy.py <__init__>82 :  Policy file is given: , but policy type is set to hdc. Ignoring the given policy file and using hdc policy.
WARNING:: 11:07:03: root                            Agent.py <_logical_requirements>405 :  Enforcing hello() at first turn in singledomain system
WARNING:: 11:07:03: root                                             Texthub.py <run>87 :  NOTE: texthub is not using any error simulation at present.
DIAL   :: 11:07:03: root                                       Agent.py <start_call>170 :  >> NEW DIALOGUE SESSION. Number: 1
INFO   :: 11:07:03: root                                    Agent.py <_hand_control>470 :  Domain Films is both already running and has control
DIAL   :: 11:07:03: root                                      Agent.py <_print_turn>579 :  ** Turn 0 **
DIAL   :: 11:07:03: root                                   Agent.py <_print_sys_act>595 :  | Sys > hello()
DIAL   :: 11:07:03: root                                     Agent.py <_agents_semo>680 :  Domain with CONTROL: Films
DIAL   :: 11:07:05: root                                    Agent.py <continue_call>232 :  user input: [('horreur', 1.0)]
DIAL   :: 11:07:05: root                                      Agent.py <_print_turn>579 :  ** Turn 1 **
INFO   :: 11:07:05: root                              TopicTracking.py <track_topic>146 :  After user_act - domain is now: Films
INFO   :: 11:07:05: root                                    Agent.py <_hand_control>470 :  Domain Films is both already running and has control
INFO   :: 11:07:05: root               SemIContextUtils.py <_add_context_to_user_act>61 :  Possibly adding context to user semi hyps: [[u'inform(genre=epouvante_horreur)', 1.0]]
INFO   :: 11:07:05: root                                            SemI.py <decode>201 :  [('inform(genre=epouvante_horreur)', 1.0)]
INFO   :: 11:07:05: root               SemIContextUtils.py <_add_context_to_user_act>61 :  Possibly adding context to user semi hyps: [('inform(genre=epouvante_horreur)', 1.0)]
INFO   :: 11:07:05: root         ModularSemanticBeliefTracker.p <update_belief_state>86 :  SemI   > [('inform(genre=epouvante_horreur)', 1.0)]
DIAL   :: 11:07:05: root                                   Agent.py <_print_sys_act>595 :  | Sys > inform(name="none",genre="epouvante_horreur")
DIAL   :: 11:07:05: root                                     Agent.py <_agents_semo>680 :  Domain with CONTROL: Films
WARNING:: 11:07:06: root                              RuleSemOMethods.py <transform>570 :  While transforming inform(name="none",genre="epouvante_horreur"), there were missing items.
ERROR  :: 11:07:06: root                              ContextLogger.py <_exceptHook>263 :  Uncaught exception: <type 'exceptions.KeyError'>( u'$R' )
          Traceback (most recent call last):
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/pydial.py", line 1143, in <module>
              run()
            File "/home/casanova/.local/lib/python2.7/site-packages/scriptine/command.py", line 196, in autocmds
              add_verbosity_option=add_verbosity_option)
            File "/home/casanova/.local/lib/python2.7/site-packages/scriptine/command.py", line 105, in parse_and_run_function
              return function(*args[:len(required_args)], **kw)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/pydial.py", line 1130, in chat_command
              hub.run()
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/Texthub.py", line 118, in run
              sys_act = self.agent.continue_call(asr_info = [(obs,1.0)], domainString = domain)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/Agent.py", line 283, in continue_call
              self.prompt_str = self._agents_semo(sys_act)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/Agent.py", line 681, in _agents_semo
              prompt_str = self.semo_manager.generate(sys_act, domainTag=self.topic_tracker.operatingDomain)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/semo/SemOManager.py", line 151, in generate
              return self.semoManagers[domainTag].generate(act_s)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/semo/RuleSemOMethods.py", line 653, in generate
              return self.generator.transform(act)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/semo/RuleSemOMethods.py", line 574, in transform
              best = self.compute_ftn(best, best_non_term_map)
            File "/home/casanova/master/s3/application_innovation/Application Interaction vocale/projet_robotparlant/PyDial/semo/RuleSemOMethods.py", line 614, in compute_ftn
              ftn_args[j] = non_term_map[arg]
          KeyError: u'$R'
          
